using System;
using System.Net.Http;
using System.Text;
using Codevoid.Utilities.OAuth;

namespace Codevoid.Instapaper
{
    /// <summary>
    /// Lightweight information about the status of a bookmark for syncing
    /// purposes. Encapsulates having the bookmark & it's state, as well as
    /// progress & progress changed information
    /// </summary>
    public readonly struct HaveStatus
    {
        /// <summary>
        ///     When you have all peices of the bookmark state, this constructor
        ///     encapsulates that information.
        /// </summary>
        /// <param name="id">Bookmark ID</param>
        /// <param name="hash">
        ///     Hash of the last status (generated by the service, not locally)
        /// </param>
        /// <param name="readProgress">
        ///     Amount of bookmark that has been read, between 0.0 and 1.0
        /// </param>
        /// <param name="changed">Last time the progress changed</param>
        public HaveStatus(string id, string hash, double readProgress, DateTimeOffset changed) : this(id, hash)
        {
            this.ReadProgress = readProgress;
            this.Changed = changed;
        }

        /// <summary>
        /// When you only have -- or only want to use -- the ID information
        /// </summary>
        /// <param name="id">Bookmark ID</param>
        public HaveStatus(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                throw new ArgumentNullException("id", "id of the bookmark is required");
            }

            this.Id = id;
            this.Hash = String.Empty;
            this.ReadProgress = null;
            this.Changed = null;
        }

        /// <summary>
        /// With an ID & hash, you can use this constructor
        /// </summary>
        /// <param name="id"></param>
        /// <param name="hash"></param>
        public HaveStatus(string id, string hash) : this(id)
        {
            if (String.IsNullOrWhiteSpace(hash))
            {
                throw new ArgumentNullException("hash", "Hash required for this bookmark");
            }

            this.Hash = hash;
        }

        /// <summary>
        /// ID of the bookmark, as originally from the service
        /// </summary>
        public string Id { get; }

        /// <summary>
        /// Service provided hash of the bookmark state. Can't be derived locally
        /// </summary>
        public string Hash { get; }

        /// <summary>
        /// The read progress of this bookmark as a percentage from 0.0 to 1.0
        /// </summary>
        public double? ReadProgress { get; }

        /// <summary>
        /// The unix epoch time that the progress was last updated.
        /// </summary>
        public DateTimeOffset? Changed { get; }

        /// <summary>
        /// The 'have' syntax is a very specific string, so overriding it here
        /// allows us to format it correctly. For more details on this format
        /// see <see href="https://www.instapaper.com/api">here</see>
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            StringBuilder haveText = new StringBuilder(this.Id);

            if (!String.IsNullOrWhiteSpace(this.Hash))
            {
                haveText.AppendFormat(":{0}", this.Hash);
            }

            if (this.ReadProgress != null && this.Changed != null)
            {
                haveText.AppendFormat(":{0}:{1}", this.ReadProgress, this.Changed?.ToUnixTimeSeconds());
            }

            return haveText.ToString();
        }
    }

    /// <summary>
    /// Bookmark operations for Instapaper -- adding removing, changing states
    /// </summary>
    public class Bookmarks
    {
        private readonly ClientInformation clientInformation;
        private readonly HttpClient client;

        public Bookmarks(ClientInformation clientInformation)
        {
            this.clientInformation = clientInformation;
            this.client = OAuthMessageHandler.CreateOAuthHttpClient(clientInformation);
        }
    }
}
