<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Codevoid.Instapaper</RootNamespace>
    <Description>Instapaper API Wrapper for Storyvoid</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\OAuthLibrary\OAuthLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.6" />
  </ItemGroup>
</Project>
